services:
    app:
        image: adcp-mcp-ui:latest
        container_name: adcp-mcp-ui
        build:
          context: .
          dockerfile: ./docker/Dockerfile
        working_dir: /app
        user: "${HOST_UID:?err}:${HOST_GID:?err}"
        entrypoint: ["node", "server.mjs"]
        volumes:
            - ./app:/app
        ports:
            - '3851:3000'
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY:-}
            ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
            VALID_ADCP_AUTH_KEYS: ${VALID_ADCP_AUTH_KEYS:-}
            BASIC_AUTH_USER: ${BASIC_AUTH_USER:-}
            BASIC_AUTH_PASS: ${BASIC_AUTH_PASS:-}
            MCP_SERVER_CHOICES: ${MCP_SERVER_CHOICES:-}

